### ISSUE TITLE
Compilation error with Wireshark SVN repo

### ISSUE THREAD

**Issue by xplico** [davidgfnet/wireshark-whatsapp#10] opened 2014-01-25 17:47 UTC
Hi,
there are some errors if we compile this code using Wireshark dev repository.
To solve them, add as first parameter to the tvb_memdup function (line 62 and 78 of packet-whatsapp.c) NULL.

Ciao.
Gianluca

**Comment by davidgfnet** [comment] 2015-01-11 02:55
This is fixed now! I just could reproduce the error due to my wireshark being updated.

**Closed by davidgfnet** 2015-01-11 02:55 UTC
